version: '3'

services:
  persons-app:
    build: ./node-js
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    command: "npm start"
    volumes:
      - ./node-js:/usr/app/
    ports:
      - 8080:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.4
    environment:
         - AUTH=no
         - MONGODB_USER="user"
         - MONGODB_PASS="pass"
    ports:
      - 27017:27017

  persons-app-frontend:
    build: ./my-react-app
    ports:
      - 80:80
    links:
      - persons-app